services:
  django-env:
    image: mdssoccer2026/ubc-mds-soccer-capstone-2026:542994f94f470bda477726079f0ec474b9374974-django
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:8000"
    volumes:
      - ./chatbot-service-account-key.json:/app/service-account-key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    working_dir: /app
    command: ["python", "app/manage.py", "runserver", "0.0.0.0:8000"]
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/arm64

  jupyter-env:
    image: mdssoccer2026/ubc-mds-soccer-capstone-2026:542994f94f470bda477726079f0ec474b9374974-jupyter
    restart: unless-stopped
    environment:
      - NB_UID=1000
      - NB_GID=1000
    ports:
      - "8888:8888"
    working_dir: /home/jovyan/work
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser"]
    platform: linux/arm64

  dagster-env:
    image: mdssoccer2026/ubc-mds-soccer-capstone-2026:542994f94f470bda477726079f0ec474b9374974-dagster
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./repo/dagster_home:/opt/dagster/dagster_home
      - ./repo:/opt/dagster/app
      - ./dagster-service-account-key.json:/opt/dagster/app/dagster-service-account-key.json:ro
    working_dir: /opt/dagster/app
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/dagster/app/dagster-service-account-key.json
      - DBT_PROFILES_DIR=/opt/dagster/app
    command: ["bash", "-c", "dbt deps && dbt parse && dagster dev -h 0.0.0.0 -p 3000 -f src/dagster/definitions.py"]
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/arm64