services:
  django-env:
    image: mdssoccer2026/ubc-mds-soccer-capstone-2026:dc2a97c44b9b4973af16610009fb99206d68c638
    restart: unless-stopped
    environment:
      - NB_UID=1000
      - NB_GID=1000
    ports:
      - "80:8000"
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/arm64

  dagster-env:
    image: mdssoccer2026/ubc-mds-soccer-capstone-2026:dc2a97c44b9b4973af16610009fb99206d68c638-dagster
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/dagster/app
    working_dir: /opt/dagster/app
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-f", "definitions.py"]
    deploy:
      resources:
        limits:
          memory: 3G
    platform: linux/arm64