name: soccer_capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - ipykernel
  - pandas
  - pyarrow
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - xgboost
  - pip:
    - duckdb
    - django
    - djangorestframework
    - django-htmx
    - groq
    - dagster
    - dagster-webserver
    - dagster-dbt
    - dbt-bigquery
    - dbt-core
    - google-cloud-bigquery
    - google-cloud-storage
    - statsbombpy
    - python-dotenv
    - joblib