name: soccer_capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - ipykernel
  - pandas
  - pyarrow
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pip:
    - duckdb
    # statsbomb
    - statsbombpy
    # gcp
    - google-cloud-storage
    - google-cloud-bigquery
    - google-cloud-bigquery-storage
    # env
    - python-dotenv
    # dbt
    - dbt-core
    - dbt-bigquery
    # dagster
    - dagster
    - dagster-webserver
    - dagster-dbt
    - dagster-gcp
    # django + chatbot
    - django
    - djangorestframework
    - django-htmx
    - groq
    # ml
    - xgboost
    - plotly
    # testing
    - pytest
