# chatbot/table_schema.py

# Ensure this name is exactly TABLE_CONTEXT
TABLE_CONTEXT = """
Available BigQuery Tables:
1. `mart_player_performance`: Contains per-90 metrics...
2. `mart_player_clusters`: Contains player names and archetypes...
3. `mart_match_analysis`: Match results and xG...
4. `mart_team_comparison`: Rolling form metrics...
"""