version: 2

sources:
  - name: statsbomb
    database: football-capstone-mds-496219
    schema: raw_statsbomb
    config:
      freshness:
        warn_after: {count: 7, period: day}
        error_after: {count: 30, period: day}
      loaded_at_field: match_date
    tables:
      - name: matches
      - name: events
      - name: lineups
      - name: reference
      - name: three_sixty

  - name: ml_models
    database: football-capstone-mds-496219
    schema: analytics
    tables:
      - name: cluster_assignments